version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  publish:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: list repo
          command: ls -la
      # - run:
      #     name: Authenticate with registry
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      # - run:
      #     name: Publish package
      #     command: npm publish
      # - run:
      #     name: Github Release
      #     command: yarn release -y
      # - run:
      #     name: Storybook
      #     command: yarn deploy-storybook --ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            # branches:
            #   only: master
            # tags:
            #   only: /^v.*/
